import React from "react";
import { Download, Trash2, FileText, Loader2 } from "lucide-react";
import Card from "../Card/Card";
import StatusBadge from "../StatusBadge/StatusBadge";
import Button from "../Button/Button";
import EmptyState from "../EmptyState/EmptyState";

export const ReportHistory = ({ reports = [], onDelete }) => {
  if (!reports.length) {
    return (
      <Card title="Report History" subtitle="Previously generated reports">
        <EmptyState title="No reports generated" description="Generate your first report to see it here." />
      </Card>
    );
  }

  return (
    <Card title="Report History" subtitle={`${reports.length} previously generated reports`}>
      <div style={{ overflowX: "auto" }}>
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr>
              {["Title", "Type", "Generated By", "Date", "Format", "Status", "Size", "Actions"].map((h) => (
                <th
                  key={h}
                  style={{
                    padding: "0.625rem 0.875rem",
                    textAlign: "left",
                    fontSize: "0.7rem",
                    fontWeight: 700,
                    color: "var(--text-muted)",
                    textTransform: "uppercase",
                    letterSpacing: "0.05em",
                    borderBottom: "1px solid var(--border-color)",
                    whiteSpace: "nowrap"
                  }}
                >
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {reports.map((report) => (
              <tr
                key={report.id}
                style={{ borderBottom: "1px solid var(--border-color)", transition: "background var(--transition-fast)" }}
                onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = "var(--bg-primary)")}
                onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = "transparent")}
              >
                <td style={{ padding: "0.75rem 0.875rem", fontSize: "0.85rem", fontWeight: 600, maxWidth: "260px", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                  {report.title}
                </td>
                <td style={{ padding: "0.75rem 0.875rem", fontSize: "0.85rem" }}>
                  <span style={{
                    display: "inline-block",
                    padding: "0.2rem 0.5rem",
                    borderRadius: "var(--radius-xs)",
                    backgroundColor: "color-mix(in srgb, var(--primary) 12%, transparent)",
                    color: "var(--primary)",
                    fontWeight: 700,
                    fontSize: "0.75rem"
                  }}>
                    {report.type}
                  </span>
                </td>
                <td style={{ padding: "0.75rem 0.875rem", fontSize: "0.85rem", color: "var(--text-secondary)" }}>{report.generatedBy}</td>
                <td style={{ padding: "0.75rem 0.875rem", fontSize: "0.85rem", color: "var(--text-secondary)" }}>{report.date}</td>
                <td style={{ padding: "0.75rem 0.875rem", fontSize: "0.85rem", fontWeight: 600 }}>{report.format}</td>
                <td style={{ padding: "0.75rem 0.875rem" }}>
                  {report.status === "Ready" ? (
                    <StatusBadge status="Active" />
                  ) : (
                    <span style={{ display: "inline-flex", alignItems: "center", gap: "0.25rem", fontSize: "0.8rem", color: "var(--warning)", fontWeight: 600 }}>
                      <Loader2 size={12} className="spin" /> Generating
                    </span>
                  )}
                </td>
                <td style={{ padding: "0.75rem 0.875rem", fontSize: "0.85rem", color: "var(--text-muted)" }}>{report.size}</td>
                <td style={{ padding: "0.75rem 0.875rem" }}>
                  <div style={{ display: "flex", gap: "0.375rem" }}>
                    <button
                      title="Download"
                      disabled={report.status !== "Ready"}
                      style={{
                        display: "flex", alignItems: "center", justifyContent: "center",
                        width: "28px", height: "28px", borderRadius: "var(--radius-xs)",
                        border: "1px solid var(--border-color)", background: "var(--bg-secondary)",
                        color: "var(--primary)", cursor: report.status === "Ready" ? "pointer" : "not-allowed",
                        opacity: report.status === "Ready" ? 1 : 0.4
                      }}
                    >
                      <Download size={13} />
                    </button>
                    <button
                      title="Delete"
                      onClick={() => onDelete(report.id)}
                      style={{
                        display: "flex", alignItems: "center", justifyContent: "center",
                        width: "28px", height: "28px", borderRadius: "var(--radius-xs)",
                        border: "1px solid var(--border-color)", background: "var(--bg-secondary)",
                        color: "var(--danger)", cursor: "pointer"
                      }}
                    >
                      <Trash2 size={13} />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Card>
  );
};

export default ReportHistory;
