import React from "react";
import { Wrench, Calendar, ClipboardList, CheckCircle2, AlertOctagon, HelpCircle } from "lucide-react";

export const MaintenanceTimeline = ({ timeline = [], status }) => {
  const getIcon = (title) => {
    const t = title.toLowerCase();
    if (t.includes("scheduled")) return <Calendar size={14} />;
    if (t.includes("sent") || t.includes("workshop")) return <Wrench size={14} />;
    if (t.includes("inspection") || t.includes("diagnostic")) return <ClipboardList size={14} />;
    if (t.includes("completed") || t.includes("ready") || t.includes("closed")) return <CheckCircle2 size={14} />;
    if (t.includes("cancelled")) return <AlertOctagon size={14} />;
    return <HelpCircle size={14} />;
  };

  const getColor = (title) => {
    const t = title.toLowerCase();
    if (t.includes("completed") || t.includes("ready") || t.includes("closed")) return "var(--success)";
    if (t.includes("cancelled") || t.includes("failure")) return "var(--danger)";
    if (t.includes("repair") || t.includes("inspection")) return "var(--warning)";
    return "var(--primary)";
  };

  const list = timeline.length > 0 ? timeline : [
    { title: "Maintenance Scheduled", description: "Servicing ticket order generated by depot operator.", date: "2026-07-12 10:00" }
  ];

  return (
    <div style={{ padding: "0.5rem 0", display: "flex", flexDirection: "column", gap: "1.5rem", position: "relative" }}>
      <div style={{
        position: "absolute",
        left: "15px",
        top: "10px",
        bottom: "10px",
        width: "2px",
        backgroundColor: "var(--border-color)",
        zIndex: 0
      }} />

      {list.map((ev, idx) => {
        const color = getColor(ev.title);
        return (
          <div key={idx} style={{ display: "flex", gap: "1.25rem", zIndex: 1, position: "relative" }}>
            <div style={{
              width: "32px",
              height: "32px",
              borderRadius: "50%",
              backgroundColor: "var(--bg-secondary)",
              border: `2px solid ${color}`,
              color: color,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              flexShrink: 0
            }}>
              {getIcon(ev.title)}
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: "0.25rem" }}>
              <span style={{ fontSize: "0.8rem", color: "var(--text-muted)", fontWeight: 600 }}>{ev.date}</span>
              <strong style={{ fontSize: "0.9rem", color: "var(--text-primary)" }}>{ev.title}</strong>
              <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)", lineHeight: 1.4 }}>{ev.description}</p>
            </div>
          </div>
        );
      })}
    </div>
  );
};

export default MaintenanceTimeline;
