export const MOCK_FUEL_LOGS = [
  {
    id: "fuel-1",
    vehicle: "Mercedes Sprinter (FL-1278)",
    driver: "David Miller",
    tripId: "TR-1001",
    fuelStation: "Shell Station #4, Miami, FL",
    fuelType: "Diesel",
    quantity: 65,
    costPerUnit: 1.36,
    totalCost: 88.40,
    currentOdometer: 112065,
    invoiceNumber: "INV-FL-1001",
    paymentMethod: "Card",
    date: "2026-07-11",
    remarks: "Refueled during delivery run. Invoice attached."
  },
  {
    id: "fuel-2",
    vehicle: "Freightliner Cascadia (TX-9082)",
    driver: "Marcus Vance",
    tripId: "TR-1002",
    fuelStation: "Chevron Plaza, Huntsville, TX",
    fuelType: "Diesel",
    quantity: 120,
    costPerUnit: 1.40,
    totalCost: 168.00,
    currentOdometer: 145200,
    invoiceNumber: "INV-FL-1002",
    paymentMethod: "Credit",
    date: "2026-07-12",
    remarks: "Fleet gas card swipe. Standard commercial refuel."
  },
  {
    id: "fuel-3",
    vehicle: "Volvo VNL 860 (NY-8832)",
    driver: "Sarah Connor",
    tripId: "TR-1003",
    fuelStation: "Exxon Express, Bronx, NY",
    fuelType: "Diesel",
    quantity: 110,
    costPerUnit: 1.40,
    totalCost: 154.00,
    currentOdometer: 88900,
    invoiceNumber: "INV-FL-1003",
    paymentMethod: "UPI",
    date: "2026-07-12",
    remarks: "Authorized gate pass refuel."
  },
  {
    id: "fuel-4",
    vehicle: "Ford Transit-350 (CA-4521)",
    driver: "John Doe",
    tripId: "TR-1004",
    fuelStation: "Pilot Travel Center, Barstow, CA",
    fuelType: "Petrol",
    quantity: 45,
    costPerUnit: 1.25,
    totalCost: 56.25,
    currentOdometer: 68120,
    invoiceNumber: "INV-FL-1004",
    paymentMethod: "Cash",
    date: "2026-07-08",
    remarks: "Reimbursed local ground run."
  },
  {
    id: "fuel-5",
    vehicle: "Mercedes Sprinter (FL-1278)",
    driver: "David Miller",
    tripId: "TR-1006",
    fuelStation: "BP Connect, Orlando, FL",
    fuelType: "Diesel",
    quantity: 50,
    costPerUnit: 1.34,
    totalCost: 67.00,
    currentOdometer: 111800,
    invoiceNumber: "INV-FL-1006",
    paymentMethod: "Bank Transfer",
    date: "2026-07-09",
    remarks: "Pre-dispatch topping."
  }
];
export default MOCK_FUEL_LOGS;
