export const MOCK_MAINTENANCE = [
  {
    id: "maint-1",
    vehicle: "Ford Transit-350 (CA-4521)",
    plateNumber: "CA-4521",
    type: "Brake Service",
    category: "Corrective",
    priority: "High",
    workshop: "West Coast Fleet Hub",
    mechanic: "Alex Rover",
    scheduledDate: "2026-07-11",
    estimatedCompletion: "2026-07-15",
    cost: 450.00,
    description: "Brake pad replacement and rotor resurfacing due to squealing reports.",
    partsRequired: "Front Brake Pads, Brake Rotors",
    remarks: "Grounded in shop. Assigned to mechanic Alex Rover.",
    status: "In Progress"
  },
  {
    id: "maint-2",
    vehicle: "Freightliner Cascadia (TX-9082)",
    plateNumber: "TX-9082",
    type: "Oil Change",
    category: "Preventive",
    priority: "Low",
    workshop: "Houston Fleet Yard #3",
    mechanic: "Dave Miller",
    scheduledDate: "2026-06-15",
    estimatedCompletion: "2026-06-15",
    cost: 180.00,
    description: "Engine oil change, oil filter replacement, and tire rotation audit.",
    partsRequired: "Engine Oil (15W-40), Oil Filter, Air Filter",
    remarks: "Completed on-time. No anomalies detected.",
    status: "Completed"
  },
  {
    id: "maint-3",
    vehicle: "Volvo VNL 860 (NY-8832)",
    plateNumber: "NY-8832",
    type: "Engine Service",
    category: "Preventive",
    priority: "Medium",
    workshop: "New York East Hub",
    mechanic: "Sarah Jenkins",
    scheduledDate: "2026-07-20",
    estimatedCompletion: "2026-07-22",
    cost: 320.00,
    description: "Transmission fluid flush and filter replacement.",
    partsRequired: "Transmission Fluid, Filter Gasket",
    remarks: "Scheduled upcoming maintenance booking.",
    status: "Scheduled"
  },
  {
    id: "maint-4",
    vehicle: "Mercedes Sprinter (FL-1278)",
    plateNumber: "FL-1278",
    type: "Battery Replacement",
    category: "Breakdown",
    priority: "Critical",
    workshop: "Miami Express Garage",
    mechanic: "Mike Chen",
    scheduledDate: "2026-07-02", // Overdue! (Today is 2026-07-12)
    estimatedCompletion: "2026-07-03",
    cost: 210.00,
    description: "Battery failure. Vehicle failed to start at loading bay.",
    partsRequired: "12V Commercial Heavy-Duty Battery",
    remarks: "Overdue maintenance task. Needs dispatch assignment or reschedule.",
    status: "Overdue"
  },
  {
    id: "maint-5",
    vehicle: "Peterbilt 579 (NV-5092)",
    plateNumber: "NV-5092",
    type: "Tyre Replacement",
    category: "Preventive",
    priority: "Medium",
    workshop: "Vegas Highway Maintenance",
    mechanic: "Alex Rover",
    scheduledDate: "2026-04-10",
    estimatedCompletion: "2026-04-10",
    cost: 1200.00,
    description: "Complete steer tires replacement before highway hauls.",
    partsRequired: "Michelin Commercial Steer Tires (x2)",
    remarks: "Cancelled. Vehicle was retired from active fleet instead.",
    status: "Cancelled"
  }
];
export default MOCK_MAINTENANCE;
