export const MOCK_TRIPS = [
  {
    id: "TR-1001",
    vehicle: "Mercedes Sprinter (FL-1278)",
    driver: "David Miller",
    source: "Miami, FL",
    destination: "Orlando, FL",
    cargoDescription: "Medical Diagnostics Vaccines",
    cargoWeight: 1200,
    vehicleCapacity: 3500,
    plannedDistance: 235,
    expectedDuration: 4,
    notes: "Temperature-sensitive cargo. Deliver directly to Health Depot.",
    priority: "High",
    dispatchDate: "2026-07-11",
    expectedCompletion: "2026-07-11",
    status: "Completed",
    createdDate: "2026-07-10"
  },
  {
    id: "TR-1002",
    vehicle: "Freightliner Cascadia (TX-9082)",
    driver: "Marcus Vance",
    source: "Houston, TX",
    destination: "Dallas, TX",
    cargoDescription: "Heavy Steel Structural Coils",
    cargoWeight: 42000,
    vehicleCapacity: 45000,
    plannedDistance: 240,
    expectedDuration: 5,
    notes: "Flatbed payload. Wrap coils securely with commercial tarps.",
    priority: "High",
    dispatchDate: "2026-07-12",
    expectedCompletion: "2026-07-12",
    status: "Dispatched",
    createdDate: "2026-07-11"
  },
  {
    id: "TR-1003",
    vehicle: "Volvo VNL 860 (NY-8832)",
    driver: "Sarah Connor",
    source: "New York, NY",
    destination: "Boston, MA",
    cargoDescription: "Industrial Generator Machinery",
    cargoWeight: 28000,
    vehicleCapacity: 50000,
    plannedDistance: 215,
    expectedDuration: 4.5,
    notes: "Requires wide turn logistics warnings. Avoid state bypass construction.",
    priority: "Medium",
    dispatchDate: "2026-07-12",
    expectedCompletion: "2026-07-12",
    status: "Dispatched",
    createdDate: "2026-07-11"
  },
  {
    id: "TR-1004",
    vehicle: "Ford Transit-350 (CA-4521)",
    driver: "John Doe",
    source: "Los Angeles, CA",
    destination: "San Francisco, CA",
    cargoDescription: "Retail E-Commerce Packages",
    cargoWeight: 3100,
    vehicleCapacity: 4500,
    plannedDistance: 380,
    expectedDuration: 7,
    notes: "Overnight ground distribution log. Deliver to hub #4.",
    priority: "Medium",
    dispatchDate: "2026-07-13",
    expectedCompletion: "2026-07-14",
    status: "Draft",
    createdDate: "2026-07-12"
  },
  {
    id: "TR-1005",
    vehicle: "Mercedes Sprinter (FL-1278)",
    driver: "David Miller",
    source: "Tampa, FL",
    destination: "Miami, FL",
    cargoDescription: "Perishable Seafood Pallets",
    cargoWeight: 2500,
    vehicleCapacity: 3500,
    plannedDistance: 280,
    expectedDuration: 5.5,
    notes: "Reefer malfunction reported at load-out. Logged cancellation.",
    priority: "High",
    dispatchDate: null,
    expectedCompletion: null,
    status: "Cancelled",
    createdDate: "2026-07-05",
    cancelReason: "Refrigeration Unit Malfunction",
    cancelNotes: "Thermostat failed to drop below 38F. Safe cargo integrity at risk."
  },
  {
    id: "TR-1006",
    vehicle: "Volvo VNL 860 (NY-8832)",
    driver: "Sarah Connor",
    source: "Philadelphia, PA",
    destination: "New York, NY",
    cargoDescription: "Commercial Kitchen Appliances",
    cargoWeight: 14000,
    vehicleCapacity: 50000,
    plannedDistance: 95,
    expectedDuration: 2.5,
    notes: "Standard commercial appliances delivery to restaurant chain.",
    priority: "Low",
    dispatchDate: "2026-07-09",
    expectedCompletion: "2026-07-09",
    status: "Completed",
    createdDate: "2026-07-08"
  }
];
export default MOCK_TRIPS;
